Reuseable workflow build unit test
dpc-sdp/github-actions pull request #18
Opened 2023-11-09 05:57 UTC by FleetAdmiralButter

2023-11-09 06:14 UTC, nicksantamaria commented on .github/workflows/build_unit-test.yml
> +name: Reusable CI/CD Workflow
```suggestion
name: Reusable workflow for ripple builds
```

2023-11-09 06:21 UTC, nicksantamaria requested changes

2023-11-09 06:21 UTC, nicksantamaria commented on .github/workflows/run_db_trigger.yml
> +name: Reusable View MySQL Tables Workflow
```suggestion
name: Reusable workflow to build MySQL database images 
```

2023-11-09 06:21 UTC, nicksantamaria commented on .github/workflows/run_db_trigger.yml
> +  view_tables:
Can we rename the job to something more meaningful?

2023-11-09 06:21 UTC, nicksantamaria commented on .github/workflows/run_db_trigger.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
This should be a slack webhook for the sdp slack org.

2023-11-09 06:21 UTC, nicksantamaria commented on .github/workflows/run_db_trigger.yml
> +          channel: '#dpc-devops-internal'
Need this updated to `#dpc-events`

2023-11-10 00:06 UTC, GROwen requested changes
build_unit-test LGTM @FleetAdmiralButter but could you fix up the line spacing between steps please, just one line is sufficient and it'd be good if they're consistent.

2023-11-10 01:32 UTC, GROwen approved these changes

2023-11-10 01:51 UTC, merged