testing central db
dpc-sdp/github-actions pull request #19
Opened 2023-11-12 23:41 UTC by rashed-k

2023-11-15 06:08 UTC, FleetAdmiralButter requested changes

2023-11-15 06:08 UTC, FleetAdmiralButter commented on .github/workflows/run_db_trigger.yml
> +      # @todo: Move this file to Bay.
Should this be actioned before this gets merged into main?

2023-11-15 06:10 UTC, steveworley commented on .github/workflows/run_db_trigger.yml
> +      # @todo: Move this file to Bay.
Yep let's get this in the correct location before we merge, I don't think a gist is a suitable location for this.

2023-11-16 00:21 UTC, steveworley requested changes
Some small changes! Looks good.

2023-11-16 00:21 UTC, steveworley commented on .github/workflows/run_db_trigger.yml
> +env:
Do we need this at the workflow and at the job?

2023-11-16 00:21 UTC, steveworley commented on .github/workflows/run_db_trigger.yml
> +        uses: aws-actions/configure-aws-credentials@v4.0.1
```suggestion
        uses: aws-actions/configure-aws-credentials@v4
```
Should be fine to pin this to the major

2023-11-16 00:21 UTC, steveworley commented on .github/workflows/run_db_trigger.yml
> +        run: curl -o Dockerfile.seed https://raw.githubusercontent.com/dpc-sdp/github-actions/fa8427babd2143086d4f3d1579b4ad7c7a0e7e78/.docker/Dockerfile.seed
```suggestion
        run: curl -o Dockerfile.seed https://raw.githubusercontent.com/dpc-sdp/github-actions/main/.docker/Dockerfile.seed
```

I think we should pin to a branch rather than the SHA — this will fail until we merge this one.

2023-11-16 00:29 UTC, FleetAdmiralButter commented on .github/workflows/run_db_trigger.yml
> +env:
Hey @steveworley I'll remove this at the job level, it should remain here at the workflow level.

2023-11-16 01:19 UTC, steveworley approved these changes

2023-11-16 01:41 UTC, merged