[SD-324] GHA Jira Noti
dpc-sdp/github-actions pull request #55
Opened 2024-10-22 23:02 UTC by klaukl

2024-10-23 04:54 UTC, GROwen submitted a review, later dismissed

2024-10-23 05:01 UTC, GROwen commented on .github/workflows/notify_jira.yml
> +          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}' || true)  # Prevents non-zero exit code
@klaukl Is the lookup for `SCFA` too limited or will it that always be the target project?

2024-10-23 05:35 UTC, klaukl commented on .github/workflows/notify_jira.yml
> +          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}' || true)  # Prevents non-zero exit code
I was thinking that too of also allowing SRM. The problem is SRM has a different JIRA workflow so it might not make sense. Maybe might add hmmm :|

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +            exit 0  # Exit gracefully without failing the job
no need

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +        if: success() && env.JIRA_ID != ''
```suggestion
        if: env.JIRA_ID != ''
```

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +          echo "STATUS=$STATUS" >> $GITHUB_ENV
I think this stores the env var for other jobs to use

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +        if: success() && env.JIRA_ID != ''
```suggestion
        if: env.JIRA_ID != ''
```

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}  # Jira username from secrets
Do you need to use release automation specific JIRA user? if it's not a generic user, we should use `TEST_JIRA_USERNMAE`

2024-10-23 22:48 UTC, tim-yao commented on .github/workflows/test_notify_jira.yml
> +            echo "Jira issue ${JIRA_ID} not found. No comment posted."
Should this be covered by the below? I would trust the response error message more, instead of make our own message.

2024-10-23 23:07 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +            exit 0  # Exit gracefully without failing the job
Removed

2024-10-24 00:03 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}  # Jira username from secrets
I'm ok with using current robot like below unless we want to do a new one for release? @GROwen @dylankelly 
<img width="747" alt="image" src="https://github.com/user-attachments/assets/071538a8-fe62-4a6d-be85-71dadca80475">

2024-10-24 00:09 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}  # Jira username from secrets
<img width="938" alt="image" src="https://github.com/user-attachments/assets/93ee4191-52dd-428d-8e3a-cb86aba455a7">
I guess we'll need to move it into the org level secret so to give it more clarity can do
TEST_JIRA_USERNAME
TEST_JIRA_PASSWORD

2024-10-24 01:28 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +            echo "Jira issue ${JIRA_ID} not found. No comment posted."
Removed the else if. Tested failure with invalid auth. 
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/a9ef0a73-ec5e-4a82-ae90-dc1f6606d1e9">

Might need to fail the job with exit 1 if not sent?

2024-10-24 01:29 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +        if: success() && env.JIRA_ID != ''
Done

2024-10-24 01:30 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +          echo "STATUS=$STATUS" >> $GITHUB_ENV
Removed status and JIRA ID env vars. Can be access without declaring each time after >> $GITHUB_ENV

2024-10-24 01:30 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +        if: success() && env.JIRA_ID != ''
Done

2024-10-24 01:43 UTC, tim-yao submitted a review, later dismissed

2024-10-24 01:50 UTC, klaukl commented on .github/workflows/test_notify_jira.yml
> +            echo "Jira issue ${JIRA_ID} not found. No comment posted."
Removed exit 1. Will fail behind the scenes and not impact the overall workflow status

2024-10-24 02:16 UTC, tim-yao approved these changes

2024-10-24 21:55 UTC, GROwen commented on .github/workflows/notify_jira.yml
> +          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}' || true)  # Prevents non-zero exit code
I don't think the scope of this action needs to take into account the workflow of the Jira project that it's posting to, does it? If not this should be refactored to be able to extract any ID.

I use this locally

```
$(g symbolic-ref --short HEAD | cut -d '/' -f2 | awk -F '[-]{2}'  '{print $1}')
```

For the branch `topic/DDS-1234--feature` the above will return `DDS-1234`

2024-10-24 22:01 UTC, GROwen requested changes
@klaukl This cannot be reused by any workflow, this repo is for reusable actions after all. Because of that it's worth a refactor to make it more generic so it's able to be used by a wider range of workflows.

To do that start with renaming from `test_notify_jira` to just `jira_post_comment`

Then you'll want to refactor the comment portion so that the it's an input rather than being computed in the reusable action.

2024-10-28 23:00 UTC, klaukl commented on .github/workflows/notify_jira.yml
> +          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}' || true)  # Prevents non-zero exit code
I think lets limit scope to SCFA. Could do SRM as well but if SCFA is the main board thats going to be the main scope

2024-11-09 08:56 UTC, closed without merging