[SD-324] Jira test notification
dpc-sdp/github-actions pull request #56
Opened 2024-10-31 22:49 UTC by klaukl

2024-10-31 22:50 UTC, klaukl commented on .github/workflows/post_jira_comment.yml
> +          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
Should we use a TEST_JIRA_USERNAME secret to abstract out stuff used to testing?

2024-10-31 22:51 UTC, klaukl commented on .github/workflows/test_prepare_jira.yml
> +  post_jira_comment:
Moved it out as requested @GROwen

2024-11-05 22:07 UTC, klaukl commented on .github/workflows/test_prepare_jira.yml
> +name: test_prepare_jira
The one below is already post_jira_comment though

2024-11-05 22:26 UTC, tim-yao commented on .github/workflows/test_prepare_jira.yml
> +name: test_prepare_jira
Does it matter?

2024-11-05 22:27 UTC, tim-yao commented
Hey, @GROwen Keith have done a code split to make the workflow more reusable, could you please review it to see if it addresses your suggestion? Cheers!

2024-11-05 23:27 UTC, klaukl commented on .github/workflows/test_prepare_jira.yml
> +name: test_prepare_jira
Changed. Done

2024-11-05 23:36 UTC, tim-yao commented on .github/workflows/test_post_jira.yml
> +          echo "Overall workflow status: ${STATUS}"
Do we need this step?

2024-11-05 23:38 UTC, tim-yao commented on .github/workflows/test_post_jira.yml
> +          COMMENT="E2E Test - ${STATUS} on branch ${GIT_BRANCH}\n"
```suggestion
          COMMENT="E2E Test - ${inputs.status} on branch ${GIT_BRANCH}\n"
```

2024-11-05 23:38 UTC, tim-yao commented on .github/workflows/test_post_jira.yml
> +          echo "COMMENT=$COMMENT" >> $GITHUB_ENV
Do we need this env var?

2024-11-06 00:05 UTC, klaukl commented on .github/workflows/test_post_jira.yml
> +          echo "COMMENT=$COMMENT" >> $GITHUB_ENV
Removed the whole section

2024-11-06 00:31 UTC, tim-yao commented on .github/workflows/test_post_jira.yml
> +
Empty line

2024-11-06 01:33 UTC, tim-yao approved these changes

2024-11-06 05:04 UTC, klaukl commented on .github/workflows/test_prepare_jira.yml
> +  post_jira_comment:
Hey @GROwen any chances to get a check? :) Thanks

2024-11-06 20:34 UTC, GROwen requested changes

2024-11-06 20:34 UTC, GROwen commented on .github/workflows/post_jira_comment.yml
> +          echo "COMMENT=${{ inputs.comment }}" >> $GITHUB_ENV
These shouldn't be necessary. Not when using [inputs.jira_id](https://github.com/dpc-sdp/github-actions/pull/56/files#diff-f36580701d0bab22dfffbcd283525ee70e0ffc392ab23ed71f558debafefa35eR31) and [inputs.comment](https://github.com/dpc-sdp/github-actions/pull/56/files#diff-f36580701d0bab22dfffbcd283525ee70e0ffc392ab23ed71f558debafefa35eR37) which is preferred 👍

2024-11-06 20:34 UTC, GROwen commented on .github/workflows/post_jira_comment.yml
> +            echo "Failed to post comment to Jira issue ${{ inputs.jira_id }}. HTTP Code: $http_code"
Will this fail the workflow? I don't think it should but it would be good to flag the failure in a more obvious way. Maybe by [updating the jobs summary](https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/)?

2024-11-06 21:50 UTC, klaukl commented on .github/workflows/post_jira_comment.yml
> +            echo "Failed to post comment to Jira issue ${{ inputs.jira_id }}. HTTP Code: $http_code"
It won't fail the workflow - want to mass test it better when we have pushed and use it before disrupting the whole workflow.

I've added the summary message

<img width="894" alt="image" src="https://github.com/user-attachments/assets/5848603e-fe29-4dd5-8737-3f7cae568394">

2024-11-06 22:24 UTC, klaukl commented on .github/workflows/post_jira_comment.yml
> +          echo "COMMENT=${{ inputs.comment }}" >> $GITHUB_ENV
Removed

2024-11-06 23:14 UTC, klaukl commented
@GROwen changed requested done. Could you please check? Thanks

2024-11-08 04:56 UTC, GROwen approved these changes

2024-11-08 04:57 UTC, merged